apiVersion: environment.cloudbees.com/v1alpha1
kind: GitRepository
metadata:
  name: bgarrett-kubedemo2023-insurance-frontend                             
  namespace: previews
spec:
  url: https://github.com/bgarrett-kubedemo2023/insurance-frontend.git
  apiTokenSecretRef:
    name: beedemo-dev-github-token
  autoUpdateContexts:                           
  - default
